### PR TITLE
Build Fixes for Curses Version

### PR DESCRIPTION
**Pull request by NoSuck**
It builds now and sounds OK.  There is some stuttering, but I suspect that is a system issue on my end.  Thank you for this wonderful software.

By the way, I had a **difficult** time procuring OPI/OVI/OZI files but ultimately stumbled upon some [here](http://snesmusic.org/hoot/v2/?company=Studio+Twin%27kle) via [this comment](https://vgmrips.net/forum/viewtopic.php?p=2424#p2424).  Do you know of a good source?

Thank you.

```
$ ./fmpc -d 1 qouji_98/QOJI_02.OVI
FM1   0119 @000   5 101        +0 0000 ______ ___ __ 00 00 00 00 12341234      0
FM2   01DF @006   5 106 o1g+   +1 0BD5 ______ ___ __ 26 0A 00 00 12341234     10
FM3   030E @003   5 106 o3c    +0 1A6A P_____ ___ __ 00 00 00 00 12341234     10
FM4   0499 @006   5  90 o1f    +1 0B39 ______ ___ __ 26 0A 00 00 12341234     10
FM5   0570 @000   0 101 o8c+   +0 0000 ______ ___ __ 00 00 00 00 12341234      0
FM6   0571 @000   0 101 o8c+   +0 0000 ______ ___ __ 00 00 00 00 12341234      0
FMEX1 065A @000   0 101 o8c+   +0 0000 ______ ___ LR 00 00 00 00 ________      0
FMEX2 065B @000   0 101 o8c+   +0 0000 ______ ___ LR 00 00 00 00 ________      0
FMEX3 065C @000   0 101 o8c+   +0 0000 ______ ___ LR 00 00 00 00 ________      0
SSG1  0581 @000   5  14        +0 FFF3 P_____ ___ ___R ___ 00 EE T_          0
SSG2  05CF @000   5  14        +0 FFF3 P_____ ___ ___R ___ 00 EE T_          0
SSG3  061B @000   5  14        +0 FFF3 P_____ ___ ___R ___ 00 EE T_          0
RHY   0658        1
ADPCM 0659 @000   0 128 o8c+   +0 0000        __ LR          PPZ8

FM                           RHYTHM             SSG  ADPCM    @000 8 5 FFFFFFFF
TL ENV                        TL 3C PTR  LV     LV            @000 8 5 FFFFFFFF
00 3FF 00 3FF 00 3FF 00 3FF   BD  _ 0000 1C LR   00   80 LR   @000 8 5 FFFFFFFF
26 000 0D 07E 0A 161 0D 049   SD  _ 0000 1C LR   00           @000 8 5 FFFFFFFF
00 007 0D 10D 0D 347 0D 007   TOP _ 0000 1C LR   00   000000  @000 8 5 FFFFFFFF
26 000 1D 07E 0A 161 1D 049   HH  _ 0000 1C LR  NZ    00001F  @000 8 5 FFFFFFFF
00 3FF 00 3FF 00 3FF 00 3FF   TOM _ 0000 1C LR   00   000000  @000 8 5 FFFFFFFF
00 3FF 00 3FF 00 3FF 00 3FF   RIM _ 0000 1C LR                @000 8 5 FFFFFFFF
PPZ:           PVI:           PDZF: OFF
惑星ΩのＱ王子
惑星ΩのＱ王子
惑星ΩのＱ王子
```

### CODE REVIEW

**Comment by bunnylin** [comment]
There's a whole bunch of OPI and other music files here: http://modland.com/incoming/laboratory/FMPMD/

They've got an anonymous ftp if you want to download the entire directory, too.

**Comment by gzaffin** [comment]
Please un-pack [FMP multiple files rar archive with FMP and PMD modules](http://mdxoarchive.webcrow.jp/) .

**Comment by NoSuck** [comment]
Thank you both.  Those look to be excellent sources.  It was especially nice being able to run `find | grep -i '\.o[pvz]i' | tee FMP音源` through FTP.

**Comment by gzaffin** [comment]
I think that this torrent is an interesting one for FMP files
[(C77) (同人音楽) [FMP] FMP MUSIC DISK Vol.9 ＋α (mdf+mds+dcp) ](https://nyaa.si/view/107454)

**Comment by myon98** [comment]
Thank you, I've merged this contribution. Basically the curses frontend was a temporary one before gtk got implemented, and was since never touched at all. I don't think it even supports PMD because it was just a FMP player at that point.

As for the stuttering, I've experienced this as well and for me I think it's due to the PortAudio -> Alsa -> Pulseaudio indirection. I might look into that, but I'm not sure if I'll further develop this curses frontend.

**Pull request merged**
